version: '2'

labels:

    rocks.puffin.name: ghost
    rocks.puffin.subtitle: simple blogging platform for individuals
    rocks.puffin.website: https://ghost.org/
    rocks.puffin.description: |
        Ghost is a platform dedicated to one thing: Publishing. 
        It's beautifully designed, completely customisable and completely Open Source.
        Ghost allows you to write and publish your own blog, giving you the tools to make it easy and even fun to do.

services:
 
    main:
        image: loomchild/ghost
        ports: 
            - 2368
        volumes: 
            - main_data:/var/lib/ghost
        environment:
            - VIRTUAL_HOST
            - VIRTUAL_PORT=2368
        networks:
            - front
            - back
            - default

volumes:
    main_data:

networks:
    front:
        external: 
            name: "puffin_front"
    back:
        external:
            name: "puffin_back"
