version: '2'

services:
 
    main:
        image: puffinrocks/ghost:latest
        ports: 
            - 2368
        environment:
            - VIRTUAL_HOST
            - VIRTUAL_PORT=2368
            - LETSENCRYPT_HOST
            - LETSENCRYPT_EMAIL
            - LETSENCRYPT_TEST
        networks:
            - front
            - back
            - default
        volumes: 
            - main_data:/var/lib/ghost
        tmpfs:
            - /run
            - /tmp

volumes:
    main_data:

networks:
    front:
        external: 
            name: "puffin_front"
    back:
        external:
            name: "puffin_back"
